### ISSUE TITLE
Add ActivityPub actor properties

### ISSUE THREAD

**Issue by evanp** [jasnell/activitystrea.ms#14]
These are in the main AS2 namespace now.

https://www.w3.org/TR/activitypub/#actor-objects

- inbox
- outbox
- following
- followers
- liked

**Comment by evanp** [comment]
I'll add a PR to implement

**Comment by jasnell** [comment]
+1 ... thanks @evanp. In general I'm not actively supporting this code right now. If you'd like, I can give you commit rights  :-)

**Comment by evanp** [comment]
I've been doing some ActivityPub development, and I'd like to use the package to read, write, and manage AS2 objects. 

I'm happy to co-maintain the package, but I'm going to need some guidance on the internal architecture for at least a while!
