### ISSUE TITLE
Publish latest version to npm

### ISSUE THREAD

**Issue by aral** [jasnell/activitystrea.ms#23]
The version in npm is 2.0.0. The version here is 2.1.0.

CC @evanp

**Comment by evanp** [comment]
Yeah, I think @jasnell needs to make me a collaborator on npm?

James, it'd be also good to do it for these packages:

 -  activitystreams-context
 -  vocabs-as
 - vocabs-asx

**Comment by evanp** [comment]
Oh, hey; I just pushed. So, I guess James did this already!

**Comment by jasnell** [comment]
I'll get the other packages updated today. And I'll make you a collaborator on those also :)
