### ISSUE TITLE
[Support] Determining ActivityStreams at root level

### ISSUE THREAD

**Issue by sjehuda** [jasnell/activitystrea.ms#34]
> if you'd like to help, let me know

Hello,

I've built a userscript that converts [JSON Feed](https://openuserjs.org/scripts/sjehuda/JSON_Feed) into an readable HTML.

I'm adding support for [ActivityStreams](https://nu.federati.net/api/statuses/public_timeline.as).

I can determine if a file is of JSON Feed by looking into `json_file.version`, but not so in GNU social (StatusNet) ActivityStream feeds.

If I'm missing anything, please guide me.

Thank you,
Schimon

**Comment by evanp** [comment]
Look for `"@context": "https://www.w3.org/ns/activitystreams"` or something similar.

**Comment by sjehuda** [comment]
On Mon, 27 Nov 2023 20:51:33 -0800
Evan Prodromou ***@***.***> wrote:

> Look for ***@***.***": "https://www.w3.org/ns/activitystreams"` or
> something similar.
> 

The StatusNet (GNU social) document has these:

```
"generator":"GNU social 2.0.0-dev",
"title":"Federati Nu: Federated N-series GNU Social public timeline",
"totalItems":20,
```

"generator" is the only identifier, yet is a specific identifier.

See https://nu.federati.net/api/statuses/public_timeline.as

Would it be correct to assume that the ActivityStream feeds of 
GNU social lack some attributes?

**Comment by sjehuda** [comment]
See https://notabug.org/diogo/gnu-social/issues/298
