### ISSUE TITLE
Create a simple object sample has an error.

### ISSUE THREAD

**Issue by sonnybrilliant** [jasnell/activitystrea.ms#6]
When you run the first sample "Create a Simple object ", you get the following error "ReferenceError: publishedNow is not defined"

The Fix:
- It missing dot on publish(fn) 

// Create a simple object
as.object().
name('baz').
content(
    as.langmap()
        .set('en', 'bar')
        .set('fr', 'foo'))
    .publishedNow()
    .prettyWrite((err,doc) => {
    if (err) throw err;
console.log(doc);
});

**Comment by jasnell** [comment]
Fixing in master now...
